// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspCoreEmptyApp.Data;

#nullable disable

namespace aspCoreEmptyApp.Data.Migrations
{
    [DbContext(typeof(UserStoreContext))]
    partial class UserStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("aspCoreEmptyApp.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Age = 20,
                            Username = "khattab"
                        },
                        new
                        {
                            Id = "2",
                            Age = 20,
                            Username = "sami"
                        },
                        new
                        {
                            Id = "3",
                            Age = 20,
                            Username = "khaled"
                        },
                        new
                        {
                            Id = "4",
                            Age = 20,
                            Username = "omaia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
